<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Marque extends \Entities\Marque implements \Doctrine\ORM\Proxy\Proxy {
  private $_entityPersister;
  private $_identifier;
  public $__isInitialized__ = false;

  public function __construct($entityPersister, $identifier) {
    $this->_entityPersister = $entityPersister;
    $this->_identifier      = $identifier;
  }

  /** @private */
  public function __load() {
    if (!$this->__isInitialized__ && $this->_entityPersister) {
      $this->__isInitialized__ = true;

      if (method_exists($this, "__wakeup")) {
        // call this after __isInitialized__to avoid infinite recursion
        // but before loading to emulate what ClassMetadata::newInstance()
        // provides.
        $this->__wakeup();
      }

      if ($this->_entityPersister->load($this->_identifier, $this) === null) {
        throw new \Doctrine\ORM\EntityNotFoundException();
      }
      unset($this->_entityPersister, $this->_identifier);
    }
  }

  /** @private */
  public function __isInitialized() {
    return $this->__isInitialized__;
  }


  public function getId() {
    if ($this->__isInitialized__ === false) {
      return (int)$this->_identifier["id"];
    }
    $this->__load();

    return parent::getId();
  }

  public function setId($id) {
    $this->__load();

    return parent::setId($id);
  }

  public function getNom() {
    $this->__load();

    return parent::getNom();
  }

  public function setNom($nom) {
    $this->__load();

    return parent::setNom($nom);
  }

  public function getCode() {
    $this->__load();

    return parent::getCode();
  }

  public function setCode($code) {
    $this->__load();

    return parent::setCode($code);
  }

  public function getLogo() {
    $this->__load();

    return parent::getLogo();
  }

  public function setLogo($logo) {
    $this->__load();

    return parent::setLogo($logo);
  }

  public function getUrl() {
    $this->__load();

    return parent::getUrl();
  }

  public function setUrl($url) {
    $this->__load();

    return parent::setUrl($url);
  }

  public function getMagasin() {
    $this->__load();

    return parent::getMagasin();
  }

  public function setMagasin($magasin) {
    $this->__load();

    return parent::setMagasin($magasin);
  }

  public function getTailleType() {
    $this->__load();

    return parent::getTailleType();
  }

  public function setTailleType($taille) {
    $this->__load();

    return parent::setTailleType($taille);
  }

  public function __toString() {
    $this->__load();

    return parent::__toString();
  }


  public function __sleep() {
    return array('__isInitialized__', 'id', 'nom', 'code', 'logo', 'url', 'magasin', 'tailleType');
  }

  public function __clone() {
    if (!$this->__isInitialized__ && $this->_entityPersister) {
      $this->__isInitialized__ = true;
      $class                   = $this->_entityPersister->getClassMetadata();
      $original                = $this->_entityPersister->load($this->_identifier);
      if ($original === null) {
        throw new \Doctrine\ORM\EntityNotFoundException();
      }
      foreach ($class->reflFields AS $field => $reflProperty) {
        $reflProperty->setValue($this, $reflProperty->getValue($original));
      }
      unset($this->_entityPersister, $this->_identifier);
    }

  }
}